FROM redash/redash:10.1.0.b50633

ENV MAX_REQUESTS=${MAX_REQUESTS:-1000}
ENV MAX_REQUESTS_JITTER=${MAX_REQUESTS_JITTER:-100}
ENV TIMEOUT=${REDASH_GUNICORN_TIMEOUT:-60}

WORKDIR /app
CMD /usr/local/bin/gunicorn -b 0.0.0.0:$PORT --name redash -w${REDASH_WEB_WORKERS:-1} redash.wsgi:app --max-requests $MAX_REQUESTS --max-requests-jitter $MAX_REQUESTS_JITTER --timeout $TIMEOUT